### ISSUE TITLE
What do you need from me? (Contract)

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#100]
Checke die Schnittstelle Contract <> Website

- Brauchst du noch eine Funktion die im Contract fehlt?
- Funktionieren die bestehenden Funktionen für deine Website oder muss etwas angepasst werden?
- Hast du noch ideen was im Contract wichtig sein könnte?

**Comment by Yoshi20** [comment]
So weit ich weiss nichts mehr. Alles was funktionieren muss, funktioniert bereits.
Ich wüsste von nichts mehr was noch fehlt oder dazu kommen könnte.
