### ISSUE TITLE
Dead Artists AI nicht Animiert sondern Bild

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#104]
Senden an Yomi

**Comment by lucca93** [comment]
@Yoshi20 Hier ein paar Bilder zum testen:
![3](https://user-images.githubusercontent.com/43188541/199057874-611e4036-cd38-4c58-87cb-11dbe1cff281.png)
![4](https://user-images.githubusercontent.com/43188541/199057877-009c750f-13e5-465a-856d-212bd4b4a166.png)
![5](https://user-images.githubusercontent.com/43188541/199057879-5b76ec29-c8a7-4c04-b30b-d9fe58bbb4eb.png)
![1](https://user-images.githubusercontent.com/43188541/199057880-554aed91-746c-4e31-8fba-47cd14fd2a7f.png)
![2](https://user-images.githubusercontent.com/43188541/199057882-e2f01f73-da05-467f-bc82-03656f0624f6.png)

**Comment by Yoshi20** [comment]
Ha aui usprobiert, aber nur Nr. 2 gseht nach mir uf dr Sitä guät us.
