### ISSUE TITLE
HomeScreen Bild Abgeschnitten bei schwarzem Strich

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#105]
Yomi senden

**Comment by lucca93** [comment]
@Yoshi20 
Hier:
![Young man walking in the empty gallery_cropped](https://user-images.githubusercontent.com/43188541/198901402-b942dfca-45fb-466f-aec2-33ea2d7ade6c.jpg)

**Comment by Yoshi20** [comment]
Gseht komisch us. Ig würd dr height: unset & Dude komplett wäg la.

height: 100%:
<img width="1440" alt="Bildschirmfoto 2022-10-31 um 15 13 23" src="https://user-images.githubusercontent.com/1472752/199028752-170bc74b-7a7f-4643-aad2-72ed4eb18a1f.png">

height: unset:
<img width="1440" alt="Bildschirmfoto 2022-10-31 um 15 13 44" src="https://user-images.githubusercontent.com/1472752/199028803-2f6e8d0f-e8b6-450a-9504-0ebcb4bb345c.png">

**Comment by lucca93** [comment]
Ok was müessti derfür mache?

**Comment by Yoshi20** [comment]
Wenn mügläch eifach dr Dude (mit Photoshop o.ä.) usä-schnidä :D

**Comment by lucca93** [comment]
Das kanni dr biete, passt das?
Also ha kei Photoshop de ma usschniede und ersetze durch wand wird grusiiig :D
Das isch eifach originalformat aber ohni ma, wenns passt kasch close, ansunste ahmerkig:
![the empty gallery](https://user-images.githubusercontent.com/43188541/199049903-34d978d8-dfd2-4dff-b06c-e2d55ddb3bb6.jpg)
