### ISSUE TITLE
gifs Dateien sind sehr gross -> evtl. kleiner

### ISSUE THREAD

**Issue by Yoshi20** [Yoshi20/DeadArtists-Ai#11]

**Comment by lucca93** [comment]
Ich kann sie verkleinern wenn du ein paar für die Website brauchst, sie sollten aber fürs NFT selbst hochauflösend sein.

**Comment by Yoshi20** [comment]
Habe heruasgefunden: gifs sind grundsätzlich schlecht für webseiten -> alles mp4 jetzt
