### ISSUE TITLE
Demobild Shop mit Metamask

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#110]

**Comment by lucca93** [comment]
@Yoshi20 Für inputs kannst du den Issue wieder öffnen und schreiben, was ich ändern könnte:
![Shop Demo](https://user-images.githubusercontent.com/43188541/198903774-5334549b-af4b-4c15-a78a-8af8e2433b87.PNG)
![Shop Demo2](https://user-images.githubusercontent.com/43188541/198903776-f4761985-d7db-4979-8259-2227fba650f0.PNG)

**Comment by Yoshi20** [comment]
Sehr nice :)
Mal offen lassen, damit auffindbar :D

**Comment by Yoshi20** [comment]
da das Bild jetzt im Home eingebaut ist -> close
