### ISSUE TITLE
FAQ & Roadmap Inhalte überarbeiten

### ISSUE THREAD

**Issue by Yoshi20** [Yoshi20/DeadArtists-Ai#113]

**Comment by lucca93** [comment]
**Roadmap (work in progress):**

Writing a lot of code
2023 Q1 – Q2
•	Developing the Dead Artists AI art generator (python)
•	Developing the NFT concepts and smart contract (solidity)
•	Developing the website (ruby on rails, html, css, js)
•	Searching for suitable dead artists and paintings 💀
Pre-mint phase
2023 Q2 - Q3
•	Generating the NFTs (takes up to 30 days!)
•	Publishing Website, Twitter and Discord
•	Marketing & awareness
Mint phase
2023 Q3 - ? (5000 supply)
•	More marketing & awareness
•	Whitelist mint 0.03 ETH
•	Public mint 0.04 ETH
•	5 Dead Artists NFT will be randomly dropped to one of our minters wallet. You could be our lucky winner!
•	Get your unloackables directly on our website
After mint phase
•	Staking Contract implementation
•	Programming of our NFT merch shop
•	Programming of our Dead Artists AI generator (for Holders only, pay with Dead Artists Token)
Periodical Floor Sweeps
To maintain a high floor price and ensure that our early Dead Artists AI holders will be profitable, we will periodically Floor Sweep with 15% of the minted ETH.
Art Basel Switzerland
Meet us at Art Basel in Switzerland and get a surprise if you're a holder!
Art Basel Miami
* holding thumbs
To be continued...


**FAQ (work in progress):**
What is the Dead Artists AI contract address?
"aktueller contract einfügen"

What are the funds being used for?
Hiring Moderators for our Discord an Twitter page
Programming of our staking contract
Getting Merch and set up a Merch shop

**Comment by Yoshi20** [comment]
"work in progress" passt nicht hin (mobile view) und würde ich eh weglasssen.

Writing a lot of code
Würde ich nicht "2023 Q1 – Q2" sondern einfach "2022"

Pre-mint phase
Nicht "2023 Q2 - Q3" sondern "2023 Q1 - Q3"


Bei FAQ: "What are the funds being used for?" habe ich 
- Periodical Floor Sweeps
hinzugefügt


Sollte in wenigen Minuten live sein.
