### ISSUE TITLE
image_link & gif_link dürfen Nummer nicht drauf haben

### ISSUE THREAD

**Issue by Yoshi20** [Yoshi20/DeadArtists-Ai#118]
Ausserdem:
- images 700x700 (nicht 1000x1000)
- images .jpg oder .webp (nicht .png)
(- evt. sogar eine neue 300x300 Variante)

**Comment by lucca93** [comment]
Am end vo dr excel hets e neui spalte, s nft als JPG in 700x700 und ohni ID:
"nft_imagelowq_link"

Bsp: https://i.ibb.co/nkfFjnq/image.jpg
