### ISSUE TITLE
Entfernen von Max NFTs

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#123]
Im Contract ist keine Begrenzung für die NFT pro Person festgelegt (würde auch keinen Sinn machen, da man einen Neuen Wallet in ca 1min errichtet hat)
![image](https://user-images.githubusercontent.com/43188541/199046856-572668f5-92ac-4757-820b-cd501cbb008f.png)

Vorschlag:
![image](https://user-images.githubusercontent.com/43188541/199047297-9b6beb19-f2d6-40ef-a6eb-1585b21656d3.png)

**Comment by Yoshi20** [comment]
Während WL zeige ich es noch an (x/3) und entferne es dann fürs Public minting.
