### ISSUE TITLE
Entfernen Video

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#124]
Entfernen Video.
Video ein bisschen unnötig / nichtssagend / eventuell sogar negativ, es sieht auf dem Video so aus, als wäre es ganz einfach die Kunstwerke zu erstellen --> wertet das Projekt ab.
![image](https://user-images.githubusercontent.com/43188541/199048493-49e9b55d-644f-4398-881f-7940ceaacc0a.png)

**Comment by lucca93** [comment]
eventuell ersetzen durch beispiele von NFTs (überschrift ist ja the art), kann man noch überlegen

**Comment by Yoshi20** [comment]
Ja gseh ig o so. Was aber schüsch a därä Steu? Eventuell äs bessers Video?

**Comment by lucca93** [comment]
zB e bispiel vome NFT und was für traits s het
