### ISSUE TITLE
Domain Change

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#125]
Mir infos angeben zum verknüpfen der Domain zu heroku

**Comment by Yoshi20** [comment]
DNS Target:
molecular-watercress-mnq3f2mclemacgzwfgbbmkue.herokudns.com

So viel ich weiss, geht aber nur http://  und noch kein https:// auf heroku, solange wir noch nichts zahlen.

**Comment by lucca93** [comment]
Verknüpft
