### ISSUE TITLE
NFTs Seite

### ISSUE THREAD

**Issue by Yoshi20** [Yoshi20/DeadArtists-Ai#13]
Übersicht aller generierten NFT.
Mit OpenSea API?

**Comment by lucca93** [comment]
OpenSea API kann erst beantragt werden, wenn sicher ist wie wir den Mint machen (Thirdweb oder Fivertyp oder Selbermachen)

**Comment by lucca93** [comment]
OpenSea API kann erst beantragt werden, wenn sicher ist wie wir den Mint machen (Thirdweb oder Fivertyp oder Selbermachen)
