### ISSUE TITLE
Verknüpfung Website funktioniert nicht

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#130]
Ich habe die Website soweit verknüpft, fehlt bei dir noch was?
https://www.deadartists.ai/
zeigt noch nichts an

**Comment by Yoshi20** [comment]
ich zahle jetzt die $16/Monat bei Heroku bzw. sollte es jetzt gehen (da SSH Zertifikat nun vorhanden).
