### ISSUE TITLE
Review Contract

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#131]
[SolDeadArtistsAI20221105_Review.txt](https://github.com/Yoshi20/DeadArtists-Ai/files/9943647/SolDeadArtistsAI20221105_Review.txt)

**Comment by Yoshi20** [comment]
# TODOs @lucca93 

Zeile 29:
  //Price and supply
  uint256 public cost = 0.045 ether;
  uint256 public costWL = 0.035 ether;
  uint256 public maxSupply = 5000;
  uint256 public maxMintAmountPerTx = 50;
  uint256 public maxMintWL = 3;
  
Zeile 39:
  bool public paused = false;

Eventuell Zeile 64 (require(!paused, "The contract is paused!");) auf Zeile 61

Sonst sieht es meiner Meinung nach gut aus.

**Comment by lucca93** [comment]
Zeile29: done

Zeile39: Paused muss am anfang true sein, bis das WL Minting gestartet hat.
als sicherheit, sonst könnte gemintet werden, sobald die Merkle root verknüpft ist.

Zeile64: Ist auf 1 verschoben.
