### ISSUE TITLE
Review Excel File

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#133]
Excel File wurde von mir und Nakima reviewt, sortierung von NFT_RarityID basiert auf Turnover und Importance.

[Z_KuenstlerAngepasstDoppelte.xlsx](https://github.com/Yoshi20/DeadArtists-Ai/files/9975610/Z_KuenstlerAngepasstDoppelte.xlsx)

**Comment by lucca93** [comment]
Das ist in etwa die Aufteilung von Rarity Rank:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/lucca/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/lucca/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Legendary | 5%
-- | --
Epic | 10%
Rare | 15%
Uncommon | 30%
Common | 40%



</body>

</html>

**Comment by Yoshi20** [comment]
- Es het no 1 z'vieu
- Es fählä no rächt vieu painting styles
- het Giotto di Bondone einisch z'Gschlächt umgwandlet?
- Da zExcel uf github posted isch worde, isch es nun öffäntläch xD -> Es muäss auso unbedingt no nft_ipfs_token_ids neu gwürflät wärdä.

**Comment by lucca93** [comment]
Alles gemacht, nei de isch immer e maa gsi XD
ha alli painting styles manuell nochtreit
