### ISSUE TITLE
Review Contract with OS Registry

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#134]
Muss leider nochmals reviewt werden und leider keine Option zum Testen für den OS Registry Contract verfügbar, eventuell einen Testcontract auf Mainnet Publizieren?
[SolDeadArtistsAI20221112_OSReg.txt](https://github.com/Yoshi20/DeadArtists-Ai/files/9995461/SolDeadArtistsAI20221112_OSReg.txt)

**Comment by Yoshi20** [comment]
sieht okay aus, aber verstehe nicht, warum nicht testbar?

**Comment by lucca93** [comment]
Weil man die funktion der registry nicht auf dem goerli testen kann.
Wurde in foren schon bemängelt aber gibt keine lösung zur zeit.

**Comment by lucca93** [comment]
Erledigt
