### ISSUE TITLE
Excel-Einträge (Artist- & Painting-Daten) der 3 NFT auf testnet

### ISSUE THREAD

**Issue by Yoshi20** [Yoshi20/DeadArtists-Ai#40]
Brauche noch möglichst finale (Excel) Daten um das Importskript zu schreiben.

**Comment by lucca93** [comment]
[Z_KuenstlerWorkWrite.xlsx](https://github.com/Yoshi20/DeadArtists-Ai/files/9482281/Z_KuenstlerWorkWrite.xlsx)

Dies ist die korrekte Excel Liste, ich habe dir alle Werte drin gelassen und werde die Liste dann danach anpassen was du brauchst (Somit können wir die Liste ohne anpassen direkt in deine DB importieren).

Legende:
Grün: kannst du für Website nutzen
Gelb: eventuell benutzen (Problem bei Gender -> habe ich nicht von allen)
Rot: Nicht benutzen

Die dazugehörigen NFT werden noch hochgeladen (wenn alles funktioniert schliesse ich den Issue)

**Comment by lucca93** [comment]
OpenSea Testnet braucht etwa 24h bis die Metadaten aktualisiert sind, dann stimmen die Daten des Excels mit dem aktuell mit der Seite verbundenen Contracts überein.

Contract:
https://goerli.etherscan.io/address/0x766d47c9991cba47adc5f7f8da3b1e619540d756#code

OpenSea:
https://testnets.opensea.io/collection/testcontractv12
