### ISSUE TITLE
Email an Art Basel (edit)

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#41]
Ich würde gerne die Art Basel schon frühzeitig anschreiben, am besten wäre natürlich eine Bestätigung vor dem Mint zu haben, ich habe eine grobe Vorlage geschrieben, welche wir laufend anpassen können.
Das Email sollte kurz sein und trotzdem direkt zeigen, was wir vor haben und um was es in unserem Projekt geht.
Es würde als "Conversation Request" oder "Gallery Request" gesendet werden:
![image](https://user-images.githubusercontent.com/43188541/186940794-8bab198c-a0d2-4a14-ba3e-c0bc609786d3.png)

Draft to be edited (copy, edit and recomment):

Dear Art Basel Team

I was wondering if you would give an art related NFT project the opportunity to have a space at Art Basel?
...
...
We are a new art project coming soon that perfectly mixes the traditional art with the new Web3 NFT art.
I think we would be a good entry for Art basel into the rising field of NFTs.
In art basel miami, i know that NFT is already a big topic.

Website: 
www.deadartists.ai

Best regards from Basel,
Lucca Saraceno from Dead Artists AI

**Comment by Yoshi20** [comment]
Dear Art Basel Team

We're a young team of classic art lovers that are currently working on a bigger art related NFT project.
We now wondered, If you would bee so kind to give us some of your time, to check out our website and also think about giving us a space at Art Basel?

Website:
[www.deadartists.ai](http://www.deadartists.ai/)

We think that our project perfectly mixes the traditional art with the new Web3 NFT art and is therefore targeting a wide range of audience.
As much as we know, NFT is already a big topic at the Art Basel in Miami.


Best regards from Basel,
Lucca Saraceno from Dead Artists AI
