### ISSUE TITLE
Domain verknüfen "www.deadartists.ai"

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#42]
Zusammen absprechen

**Comment by Yoshi20** [comment]
DNS target:
rocky-dawn-lt8wuuq5e8c0jigjczsc5z8u.herokudns.com

**Comment by lucca93** [comment]
![image](https://user-images.githubusercontent.com/43188541/187999625-3ac36388-9f9d-4b64-9e1c-738ee2c01fa7.png)

Done, bitte mir Rückmelden, falls es nicht geklappt hat
