### ISSUE TITLE
Email vorhanden?

### ISSUE THREAD

**Issue by Yoshi20** [Yoshi20/DeadArtists-Ai#48]
z.B. postmaster@deadartist.ai

**Comment by Yoshi20** [comment]
Benötigte SMTP data:
```
host = "mail.infomaniak.com",
domain = "deadartists.ai",
user_name = ENV['INFOMANIAK_EMAIL_USERNAME']
password = ENV['INFOMANIAK_EMAIL_PASSWORD']
```

**Comment by lucca93** [comment]
https://welcome.infomaniak.com/iw/JUs7iWQaANPZsCj4ami3OnIZ2PASdCBF

host = "mail.infomaniak.com",
domain = "deadartists.ai",
user_name = postmaster@deadartists.ai
password = https://kpaste.infomaniak.com/KtZpHHf0ZI9uqRjvZW1_sl8obcZ6Sqr3#HxpA4yYYRXkknH9HhHDonrjbGzK2HzuXc9xG5gq6bwQS
