### ISSUE TITLE
Excel Liste Rückmeldung (Siehe Issue 40)

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#50]
Bitte sende mir die Excel Liste von Issue 40 so zurück wie du sie gerne hättest (einfach alle für dich irrelevanten Spalten löschen).
Falls dir ihrgendetwas fehlt, bitte Melden, eventuell kann ich es einfügen.

**Comment by Yoshi20** [comment]
Reihenfolge ist egal.
[Z_KuenstlerWorkWrite_neu.xlsx](https://github.com/Yoshi20/DeadArtists-Ai/files/9482571/Z_KuenstlerWorkWrite_neu.xlsx)

Spalten in Klammer sind nice to have.

**Comment by lucca93** [comment]
[Z_KuenstlerWorkWrite.xlsx](https://github.com/Yoshi20/DeadArtists-Ai/files/9482752/Z_KuenstlerWorkWrite.xlsx)
Falls du noch anmerkungen hast issue wieder öffnen
