### ISSUE TITLE
Traits finalisieren, impl. & testen

### ISSUE THREAD

**Issue by Yoshi20** [Yoshi20/DeadArtists-Ai#54]
Im Moment:
```
trait_artist
trait_painting
trait_main_style
trait_year_of_death
trait_gender
trait_origin
```

Fehlt (?):
```
painting_content
painting_medium
rarity
```

**Comment by Yoshi20** [comment]
Neu:
trait_movement_pattern
trait_rarity

Umbenennen:
trait_main_style -> trait_painting_style

**Comment by lucca93** [comment]
worksheet.cell(1, 26).value = "trait_movement_pattern"
Als String

Painting_rarity = trait_rarity
