### ISSUE TITLE
Erster Satz im home irreführend?

### ISSUE THREAD

**Issue by Yoshi20** [Yoshi20/DeadArtists-Ai#60]
Man könnte meinen es gibt nur Bilder dieser drei Künstler.

**Comment by Yoshi20** [comment]
Yes, you should definitely own a famous dead artist like Van Gogh, Picasso or Da Vinci for yourself!

**Comment by lucca93** [comment]
Man könnte auch was mit "and many more" machen

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
