### ISSUE TITLE
evtl. Royalities im SmartContract hinterlegen

### ISSUE THREAD

**Issue by Yoshi20** [Yoshi20/DeadArtists-Ai#63]
Bzw. funktioniert das bereits, oder muss das noch in den SmartContract?

**Comment by Yoshi20** [comment]
Im FAQ erwähnen?

**Comment by Yoshi20** [comment]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/extensions/ERC721Royalty.sol

https://eips.ethereum.org/EIPS/eip-2981#optional-royalty-payments

**Comment by lucca93** [comment]
Royalitis stellt man auf opensea im profil ein, würde ich nicht ins faq nehmen.
(Für denn testcontract hab ichs schon probiert, funktioniert)

Ich denke so etwas um 5% oder 7.5% ist angemessen.

**Comment by lucca93** [comment]
Ist gemacht
