### ISSUE TITLE
NFT Trait "Movement"

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#64]
Ein Attribut, welches beschreibt, wie sich die Person im NFT Bewegt, sinnvoll?

**Comment by Yoshi20** [comment]
Ich denk das kann man gut.
Ich würds "movement_pattern" nenne.

**Comment by Yoshi20** [comment]
https://github.com/Yoshi20/DeadArtists-Ai/issues/54

**Comment by lucca93** [comment]
worksheet.cell(1, 26).value = "movement_pattern"

**Comment by lucca93** [comment]
Als String
