### ISSUE TITLE
NFT nebst ipfs auch auf i.ibb hosten

### ISSUE THREAD

**Issue by Yoshi20** [Yoshi20/DeadArtists-Ai#69]
Yomi — heute um 21:11 Uhr
hmm... wärs äch mügläch aui NFT Biuder of uf i.ibb z'hostä?
grad gmerkt, dass ig ja gar nid würk äs nft cha a-zeigä wenn igs jewiels vo ipfs muäss ga ladä. Das isch vieu z'lahm
*natürläch parallel zu ipfs

**Comment by lucca93** [comment]
Ist gemacht, ab nächster Excel in der letzten Spalte ist der IMGBB link für das NFT
