### ISSUE TITLE
Scrolltext bewegt sich auf Mobileversion nicht

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#70]
![Screenshot_20220905-154905_Brave](https://user-images.githubusercontent.com/43188541/188464693-d41252e3-4ba1-45ee-bf63-d7e55ebecb5c.jpg)

**Comment by Yoshi20** [comment]
Good catch.
<marquee> isch schienbar deprecated -> has nöi implementiert (mit css)
