### ISSUE TITLE
Dead Artists AI handwriten text hintergrund falsch

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#71]
Ist eventuell auch mein fehler, ist dies schon das neue video? Der hintergrund passt noch nicht.
Hat die Mobileversion eine andere hintergrundfarbe als PC version?
Auf dem Screenshot siehts gut aus aber direkt im browser sieht man einen klaren unterschied.
![Screenshot_20220905-155235_Brave](https://user-images.githubusercontent.com/43188541/188465265-be7c8464-2ba0-46af-a514-2d56cb629293.jpg)

**Comment by Yoshi20** [comment]
Kann nicht sein. Ist ziemlich sicher ein caching Problem.
