### ISSUE TITLE
reveal aus SmartContract entfernen

### ISSUE THREAD

**Issue by Yoshi20** [Yoshi20/DeadArtists-Ai#76]

**Comment by lucca93** [comment]
Ich habe es nun raus genommen aber nun wieder implementiert.
Das Problem ist, wenn jemand die CID rausfindet, kann er bei uns direkt an den Traits unsere Rarity ablesen.
Die ID welches NFT als nächstes kommt ist für jeden ersichtlich.
Deshalb müssen wir es zuerst verstecken.
