### ISSUE TITLE
NFT als .mp4 auf i.ibb laden (nicht als .gif)

### ISSUE THREAD

**Issue by Yoshi20** [Yoshi20/DeadArtists-Ai#77]

**Comment by lucca93** [comment]
Ich könnte dies machen, dafür müsste ich aber jedes nft zuerst in ein mp4 convertieren (im programm mach ich zurzeit direkt gifs), was mich vermutlich nochmal  1min mehr pro nft kostet.
Welche vorteile hätte ein mp4?

**Comment by Yoshi20** [comment]
Habe heruasgefunden: gifs sind grundsätzlich schlecht für webseiten -> besser alles mp4

Mit mp4 sind es wesentlich weniger Daten (bzw. komprimierter) und besser von den Browsern unterstützt.
mp4 lädt daher ein vielfaches schneller als gif.

**Comment by lucca93** [comment]
Ich kann die GIF zu MP4 converten, durchschnittlich habe ich 11 Sekunden mehr pro NFT.
Dies sind insg. 15.2h.
Falls es mit GIFs auch geht würde ich es gerne vermeiden andernfalls kann ich es aber auch umsetzen und dann gehts halt die 15h länger.
Bitte Testen.
