### ISSUE TITLE
Rarity auf Website anpassen

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#79]
Habe Superlegendary entfernt es gibt nun folgende Rarity Stufen, dies müsste auch überall auf der Website angepasst werden:

Legendary
Epic
Rare
Uncommon
Common

**Comment by Yoshi20** [comment]
War so weit ersichtlich nur im FAQ dokumentiert.
-> Habe "Super Legendary" entfernt
