### ISSUE TITLE
in Whitelist Phase Backend Funktion für senden von "HexProof von Merkle Tree"

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#81]
Beim Minten in der Whitelist phase sollte mir zusätzlich ein Proof gesendet werden.
Können wir noch zusammen besprechen.

Schlussendlich wäre dies in der WL Phase so:
mintWL(anzahl NFTs, MerkleHexProof)

In Java sieht dies so aus:

//MODUL 1: Erstellen des Whitelist Merkle Trees (muss nur einmal ausgeführt werden um den Merkletree Hash zu bekommen)

const { MerkleTree } = require('merkletreejs');
const keccak256 = require('keccak256');

// Beispiel Adressen der Wallets auf der Whitelist:
let whitelistAddresses = [
    "0X5B38DA6A701C568545DCFCB03FCB875F56BEDDC4",
    "0X5A641E5FB72A2FD9137312E7694D42996D689D99",
    "0XDCAB482177A592E424D1C8318A464FC922E8DE40",
    "0x583031D1113aD414F02576BD6afaBfb302140225",
    "0X09BAAB19FC77C19898140DADD30C4685C597620B",
    "0XCC4C29997177253376528C05D3DF91CF2D69061A",
    "0xdD870fA1b7C4700F2BD7f44238821C26f7392148"
  ];

const leafNodes = whitelistAddresses.map(addr => keccak256(addr));
const DeadArtistsMerkleTree = new MerkleTree(leafNodes, keccak256, { sortPairs: true});

//MODUL 2 : bei klick auf Button "Mint" wärend der Whitelist phase muss dies zum Smartcontract gesendet werden 

const claimingAddress = keccak256("WALLET ADRESS MINTER");

const hexProof = DeadArtistsMerkleTree.getHexProof(claimingAddress);

//Sende mir hexProof

**Comment by Yoshi20** [comment]
Soweit möglich erledigt.

whitelistAddresses sollten via ENV['WHITELIST_ADDRESSES'] konfigurierbar sein (1 string; Adressen mit spaces getrennt).

Muss noch mit einem SmartContract getestet werden, der whitelists hat.

**Comment by Yoshi20** [comment]
Soweit möglich erledigt.

whitelistAddresses sollten via ENV['WHITELIST_ADDRESSES'] konfigurierbar sein (1 string; Adressen mit spaces getrennt).

Muss noch mit einem SmartContract getestet werden, der whitelists hat.
