### ISSUE TITLE
Team erweitern

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#83]
Basti (name wird evt no gänderet)
Community Manager

https://user-images.githubusercontent.com/43188541/191074138-4cf59333-4768-4a24-a810-b0cc6b20dd51.mp4

**Comment by Yoshi20** [comment]
Erledigt. Ein anderes "movement pattern" wäre aber vermutlich besser gewesen, da gleich wie deins.

**Comment by lucca93** [comment]
Mach ich morgen
