### ISSUE TITLE
Banner zu schmal

### ISSUE THREAD

**Issue by lucca93** [Yoshi20/DeadArtists-Ai#93]
Der banner sollte (egal wie breit der Bildschirm ist) bis an den Rand kommen (dynamische Banner).

![image](https://user-images.githubusercontent.com/43188541/193462458-caac3967-db5a-4b82-8573-5aa9a4ac8f96.png)

**Comment by Yoshi20** [comment]
technisch so (mit Hintergrund und main-Container) nicht lösbar.
