### ISSUE TITLE
excel ergänzen (image_link & color_code)

### ISSUE THREAD

**Issue by Yoshi20** [Yoshi20/DeadArtists-Ai#97]
Neu:
- mit link auf statisches Bild ohne QR code
- mit Farb-Code (hex string) für Schriftfarbe/QR-Farbe

Naming:
- nft_image_link (link ufs image ohni QR code)
- nft_animation_link oder nft_gif_link oder so ähnläch (link ufs gif)
- nft_collectible_link (link ufs image mit QR code)
- nft_color_code ("RRGGBB")

**Comment by lucca93** [comment]
Gemacht
